name: Build Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          build-args: |
            ANSIBLE_VERSION=6.0.0
            YQ_VERSION=v4.25.3
            KUSTOMIZE_VERSION=4.5.7
            HELM_VERSION=3.10.3-1
            AVP_VERSION=1.13.1
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kube-utils:v0.3, ${{ secrets.DOCKER_HUB_USERNAME }}/kube-utils:latest
